# Generated by Django 3.2.15 on 2022-10-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted_on',
            new_name='created_on',
        ),
    ]
