# Generated by Django 3.2.15 on 2022-11-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_platform', '0013_rename_user_comment_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='name',
        ),
    ]
